apiVersion: v1
kind: Service
metadata:
  name: ecshop-web
  labels:
    app: ecshop
spec:
#  type: NodePort
  ports:
    - port: 80
#      targetPort: 80
#      nodePort: 30008
  selector:
    app: ecshop
    tier: nginx-php
  sessionAffinity: ClientIP
