apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecshop-web
  labels:
    app: ecshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecshop
      tier: nginx-php
  template:
    metadata:
      labels:
        app: ecshop
        tier: nginx-php
    spec:
      imagePullSecrets:
      - name: my-secret
      containers:
      - image: 192.168.36.132/base/ecshop_web:v6
        name: ecshop-web
        ports:
        - containerPort: 9000
        - containerPort: 80
          name: ecshop-web
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/www/html/
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ecshop-web-claim
